package dev.mobile.digibanq.db;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Entity mapped to table "BUDGET_CONTENT".
 */
public class BudgetContent extends RealmObject{
    private Boolean pendingsync;
    private String lastsync;
    @PrimaryKey
    private int id;
    private int idbudgetcategory;
    private String name;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BudgetContent() {
    }

    public BudgetContent(int id) {
        this.id = id;
    }

    public BudgetContent(Boolean pendingsync, String lastsync, int id, int idbudgetcategory, String name) {
        this.pendingsync = pendingsync;
        this.lastsync = lastsync;
        this.id = id;
        this.idbudgetcategory = idbudgetcategory;
        this.name = name;
    }

    public Boolean getPendingsync() {
        return pendingsync;
    }

    public void setPendingsync(Boolean pendingsync) {
        this.pendingsync = pendingsync;
    }

    public String getLastsync() {
        return lastsync;
    }

    public void setLastsync(String lastsync) {
        this.lastsync = lastsync;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public int getIdbudgetcategory() {
        return idbudgetcategory;
    }

    public void setIdbudgetcategory(int idbudgetcategory) {
        this.idbudgetcategory = idbudgetcategory;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
