package dev.mobile.digibanq.db;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

/**
 * Entity mapped to table "BUDGET_CATEGORY".
 */
public class BudgetCategory extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
    private Boolean iscustom;
    private Boolean pendingsync;
    private String lastsync;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public BudgetCategory() {
    }

    public BudgetCategory(int id) {
        this.id = id;
    }

    public BudgetCategory(int id, String name, Boolean iscustom, Boolean pendingsync, String lastsync) {
        this.id = id;
        this.name = name;
        this.iscustom = iscustom;
        this.pendingsync = pendingsync;
        this.lastsync = lastsync;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Boolean getIscustom() {
        return iscustom;
    }

    public void setIscustom(Boolean iscustom) {
        this.iscustom = iscustom;
    }

    public Boolean getPendingsync() {
        return pendingsync;
    }

    public void setPendingsync(Boolean pendingsync) {
        this.pendingsync = pendingsync;
    }

    public String getLastsync() {
        return lastsync;
    }

    public void setLastsync(String lastsync) {
        this.lastsync = lastsync;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
