package dev.mobile.digibanq.db;

import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "CUSTOM_GOALS".
 */
public class CustomGoals extends RealmObject{

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @PrimaryKey
    private int id;

    public CustomGoals(int id) {
        this.id = id;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public CustomGoals() {
    }


    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
