package dev.mobile.digibanq.db;


import io.realm.Realm;
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "DEFAULT_GOALS".
 */
public class DefaultGoals extends RealmObject {

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END
    @PrimaryKey
    private int id;

    public DefaultGoals() {
    }

    public DefaultGoals(int id) {
        this.id = id;
    }
// KEEP METHODS - put your custom methods here
    // KEEP METHODS END

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }
}
