package dev.mobile.digibanq.db;


// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

import io.realm.Realm;
import io.realm.RealmObject;

/**
 * Entity mapped to table "EMPLOYMENT_DETAILS".
 */
public class EmploymentDetails extends RealmObject{

    private int id;

    private String companyname;

    private String jobtype;

    private String doe;

    private String location;
    private Boolean pendingsync;
    private String lastsync;

    private String employercontact;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public EmploymentDetails() {
    }

    public EmploymentDetails(int id) {
        this.id = id;
    }

    public EmploymentDetails(int id, String companyname, String jobtype, String doe, String location, Boolean pendingsync, String lastsync, String employercontact) {
        this.id = id;
        this.companyname = companyname;
        this.jobtype = jobtype;
        this.doe = doe;
        this.location = location;
        this.pendingsync = pendingsync;
        this.lastsync = lastsync;
        this.employercontact = employercontact;
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getCompanyname() {
        return companyname;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCompanyname( String companyname) {
        this.companyname = companyname;
    }

    
    public String getJobtype() {
        return jobtype;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setJobtype( String jobtype) {
        this.jobtype = jobtype;
    }

    
    public String getDoe() {
        return doe;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDoe( String doe) {
        this.doe = doe;
    }

    
    public String getLocation() {
        return location;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setLocation( String location) {
        this.location = location;
    }

    public Boolean getPendingsync() {
        return pendingsync;
    }

    public void setPendingsync(Boolean pendingsync) {
        this.pendingsync = pendingsync;
    }

    public String getLastsync() {
        return lastsync;
    }

    public void setLastsync(String lastsync) {
        this.lastsync = lastsync;
    }

    
    public String getEmployercontact() {
        return employercontact;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setEmployercontact( String employercontact) {
        this.employercontact = employercontact;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
